TRUE_FALSE_OPTIONS = [ 
  [ 'True', true ],
  [ 'False', false ] ]

FALSE_TRUE_OPTIONS = [ 
  [ 'False', false ], 
  [ 'True', true ] ]

NO_YES_OPTIONS = [ 
  [ 'No', false ], 
  [ 'Yes', true ] ]

YES_NO_OPTIONS = [ 
  [ 'Yes', true ], 
  [ 'No', false ] ]

YES_NO_DONTKNOW_OPTIONS = [ 
  [ 'Yes', '1' ],
  [ 'No', '0' ], 
  [ 'Not sure', '-1' ] ]

SCHOOL_OPTIONS = [
  [ 'Bacich Elementary School', '103' ],
  [ 'Kent Middle School', '104' ] ]
  
NEXT_SCHOOL_OPTIONS = [
  [ 'Bacich Elementary School', '103' ],
  [ 'Kent Middle School', '104' ],
  [ 'Graduating', '999999' ] ]

STAFF_SCHOOL_OPTIONS = [
  [ 'District Office', '102' ],
  [ 'Bacich Elementary School', '103' ],
  [ 'Kent Middle School', '104' ] ]
  
REG_YEAR_OPTIONS = [
  '2007-2008', '2008-2009' ]

SHORT_GRADE_LEVEL = {
  -1 => 'Pre-K',
  0 => 'K',
  1 => '1',
  2 => '2',
  3 => '3',
  4 => '4',
  5 => '5',
  6 => '6',
  7 => '7',
  8 => '8',
}

LONG_GRADE_LEVEL = {
  -1 => 'Pre-Kindergarten',
  0 => 'Kindergarten',
  1 => '1st Grade',
  2 => '2nd Grade',
  3 => '3rd Grade',
  4 => '4th Grade',
  5 => '5th Grade',
  6 => '6th Grade',
  7 => '7th Grade',
  8 => '8th Grade',
}

NEXT_GRADE_LEVEL = {
  0 => 'K',
  1 => '1',
  2 => '2',
  3 => '3',
  4 => '4',
  5 => '5',
  6 => '6',
  7 => '7',
  8 => '8',
  99 => 'Graduating'
}

NEWREG_GRADE_LEVEL_OPTIONS = [ 
  [ 'Will not be attending', '' ],
  [ 'Kindergarten - Bacich Elementary School', 0 ],
  [ '1st Grade - Bacich Elementary School', 1 ],
  [ '2nd Grade - Bacich Elementary School', 2 ],
  [ '3rd Grade - Bacich Elementary School', 3 ],
  [ '4th Grade - Bacich Elementary School', 4 ],
  [ '5th Grade - Kent Middle School', 5 ],
  [ '6th Grade - Kent Middle School', 6 ],
  [ '7th Grade - Kent Middle School', 7 ],
  [ '8th Grade - Kent Middle School', 8 ] ]

SHORT_GRADE_LEVEL_OPTIONS = [
  [ 'K', 0 ],
  [ '1', 1 ],
  [ '2', 2 ],
  [ '3', 3 ],
  [ '4', 4 ],
  [ '5', 5 ],
  [ '6', 6 ],
  [ '7', 7 ],
  [ '8', 8 ] ]

NEXT_GRADE_LEVEL_OPTIONS = [
  [ 'K', 0 ],
  [ '1', 1 ],
  [ '2', 2 ],
  [ '3', 3 ],
  [ '4', 4 ],
  [ '5', 5 ],
  [ '6', 6 ],
  [ '7', 7 ],
  [ '8', 8 ],
  [ 'Graduating', 99 ] ]

PREV_SCHOOL_GRADE_LEVEL_OPTIONS = [ 
  [ 'Pre-Kindergarten', -1 ],
  [ 'Kindergarten', 0 ],
  [ '1st Grade', 1 ],
  [ '2nd Grade', 2 ],
  [ '3rd Grade', 3 ],
  [ '4th Grade', 4 ],
  [ '5th Grade', 5 ],
  [ '6th Grade', 6 ],
  [ '7th Grade', 7 ],
  [ '8th Grade', 8 ] ]

LONG_GRADE_LEVEL_OPTIONS = [ 
  [ 'Kindergarten', 0 ],
  [ '1st Grade', 1 ],
  [ '2nd Grade', 2 ],
  [ '3rd Grade', 3 ],
  [ '4th Grade', 4 ],
  [ '5th Grade', 5 ],
  [ '6th Grade', 6 ],
  [ '7th Grade', 7 ],
  [ '8th Grade', 8 ] ]
 
KENT_GRADE_LEVEL_OPTIONS = [ 
  [ '5th Grade', 5 ],
  [ '6th Grade', 6 ],
  [ '7th Grade', 7 ],
  [ '8th Grade', 8 ] ]
  
GENDER_OPTIONS = [ 'M', 'F' ]

LIVES_WITH_OPTIONS = [ 
  [ 'Both parents', 'both' ],
  [ 'Mother', 'mother' ],
  [ 'Father', 'father' ],
  [ 'Legal guardian', 'guardian' ], 
  [ 'Other', 'other' ] ]

NASTATE_OPTIONS = [
  [ 'California', 'US-CA' ],
  [ 'Alabama', 'US-AL' ],
  [ 'Alaska', 'US-AK' ],
  [ 'Arizona', 'US-AZ' ],
  [ 'Arkansas', 'US-AR' ],
  [ 'Colorado', 'US-CO' ],
  [ 'Connecticut', 'US-CT' ],
  [ 'Delaware', 'US-DE' ],
  [ 'District of Columbia', 'US-DC' ],
  [ 'Florida', 'US-FL' ],
  [ 'Georgia', 'US-GA' ],
  [ 'Hawaii', 'US-HI' ],
  [ 'Idaho', 'US-ID' ],
  [ 'Illinois', 'US-IL' ],
  [ 'Indiana', 'US-IN' ],
  [ 'Iowa', 'US-IA' ],
  [ 'Kansas', 'US-KS' ],
  [ 'Kentucky', 'US-KY' ],
  [ 'Louisiana', 'US-LA' ],
  [ 'Maine', 'US-ME' ],
  [ 'Maryland', 'US-MD' ],
  [ 'Massachusetts', 'US-MA' ],
  [ 'Michigan', 'US-MI' ],
  [ 'Minnesota', 'US-MN' ],
  [ 'Mississippi', 'US-MS' ],
  [ 'Missouri', 'US-MO' ],
  [ 'Montana', 'US-MT' ],
  [ 'Nebraska', 'US-NE' ],
  [ 'Nevada', 'US-NV' ],
  [ 'New Hampshire', 'US-NH' ],
  [ 'New Jersey', 'US-NJ' ],
  [ 'New Mexico', 'US-NM' ],
  [ 'New York', 'US-NY' ],
  [ 'North Carolina', 'US-NC' ],
  [ 'North Dakota', 'US-ND' ],
  [ 'Ohio', 'US-OH' ],
  [ 'Oklahoma', 'US-OK' ],
  [ 'Oregon', 'US-OR' ],
  [ 'Pennsylvania', 'US-PA' ],
  [ 'Rhode Island', 'US-RI' ],
  [ 'South Carolina', 'US-SC' ],
  [ 'South Dakota', 'US-SD' ],
  [ 'Tennessee', 'US-TN' ],
  [ 'Texas', 'US-TX' ],
  [ 'Utah', 'US-UT' ],
  [ 'Vermont', 'US-VT' ],
  [ 'Virginia', 'US-VA' ],
  [ 'Washington', 'US-WA' ],
  [ 'West Virginia', 'US-WV' ],
  [ 'Wisconsin', 'US-WI' ],
  [ 'Wyoming', 'US-WY' ],
  [ '--Mexico--', '-M' ],
  [ 'Aguascalientes', 'MX-AGU' ],
  [ 'Baja California Norte', 'MX-BCN' ],
  [ 'Baja California Sur', 'MX-BCS' ],
  [ 'Chihuahua', 'MX-CHH' ],
  [ 'Colima', 'MX-COL' ],
  [ 'Campeche', 'MX-CAM' ],
  [ 'Chiapas', 'MX-CHP' ],
  [ 'Coahuila', 'MX-COA' ],
  [ 'Distrito Federal', 'MX-DIF' ],
  [ 'Durango', 'MX-DUR' ],
  [ 'Guerrero', 'MX-GRO' ],
  [ 'Guanajuato', 'MX-GUA' ],
  [ 'Hidalgo', 'MX-HID' ],
  [ 'Jalisco', 'MX-JAL' ],
  [ 'Michoacan', 'MX-MIC' ],
  [ 'Morelos', 'MX-MOR' ],
  [ 'Mexico State', 'MX-MEX' ],
  [ 'Nayarit', 'MX-NAY' ],
  [ 'Nuevo Leon', 'MX-NLE' ],
  [ 'Oaxaca', 'MX-OAX' ],
  [ 'Puebla', 'MX-PUE' ],
  [ 'Queretaro', 'MX-QUE' ],
  [ 'Quintana Roo', 'MX-ROO' ],
  [ 'Sinaloa', 'MX-SIN' ],
  [ 'San Luis Potosi', 'MX-SLP' ],
  [ 'Sonora', 'MX-SON' ],
  [ 'Tabasco', 'MX-TAB' ],
  [ 'Tamaulipas', 'MX-TAM' ],
  [ 'Tlaxcala', 'MX-TLA' ],
  [ 'Veracruz', 'MX-VER' ],
  [ 'Yucatan', 'MX-YUC' ],
  [ 'Zacatecas', 'MX-ZAC' ],
  [ '--Canada--', '-C' ],  
  [ 'Alberta', 'CA-AB' ],
  [ 'British Columbia', 'CA-BC' ],
  [ 'Manitoba', 'CA-MB' ],
  [ 'New Brunswick', 'CA-NB' ],
  [ 'Newfoundland', 'CA-NF' ],
  [ 'Nunavut', 'CA-NT' ],
  [ 'Nova Scotia', 'CA-NS' ],
  [ 'Ontario', 'CA-ON' ],
  [ 'Prince Edward I.', 'CA-PE' ],
  [ 'Quebec', 'CA-PQ' ],
  [ 'Saskatchewan', 'CA-SK' ],
  [ 'Yukon', 'CA-YT' ],
]
  
COUNTRY_OPTIONS = [
  [ 'United States', 'US' ],
  [ 'Mexico', 'MX' ], 
  [ 'Canada', 'CA' ], 
  
  [ 'Ascension Island', 'AC' ],
  [ 'Afghanistan', 'AF' ],
  [ 'Aland Islands', 'AX' ],
  [ 'Albania', 'AL' ],
  [ 'Algeria', 'DZ' ],
  [ 'American Samoa', 'AS' ],
  [ 'Argentina', 'AR' ],
  [ 'Armenia', 'AM' ],
  [ 'Aruba', 'AW' ],
  [ 'Australia', 'AU' ],
  [ 'Austria', 'AT' ],
  [ 'Azerbaijan', 'AZ' ],
  [ 'Bahamas', 'BS' ],
  [ 'Bahrain', 'BH' ],
  [ 'Bangladesh', 'BD' ],
  [ 'Barbados', 'BB' ],
  [ 'Belarus', 'BY' ],
  [ 'Belgium', 'BE' ],
  [ 'Belize', 'BZ' ],
  [ 'Benin', 'BJ' ],
  [ 'Bermuda', 'BM' ],
  [ 'Bhutan', 'BT' ],
  [ 'Bolivia', 'BO' ],
  [ 'Bosnia and Herzegovina', 'BA' ],
  [ 'Botswana', 'BW' ],
  [ 'Bouvet Island', 'BV' ],
  [ 'Brazil', 'BR' ],
  [ 'British Indian Ocean Territory', 'IO' ],
  [ 'Brunei Darussalam', 'BN' ],
  [ 'Bulgaria', 'BG' ],
  [ 'Burkina Faso', 'BF' ],
  [ 'Burundi', 'BI' ],
  [ 'Cambodia', 'KH' ],
  [ 'Cameroon', 'CM' ],
  [ 'Cape Verde', 'CV' ],
  [ 'Cayman Islands', 'KY' ],
  [ 'Central African Republic', 'CF' ],
  [ 'Chad', 'TD' ],
  [ 'Chile', 'CL' ],
  [ 'China', 'CN' ],
  [ 'Christmas Island', 'CX' ],
  [ 'Clipperton Island', 'CP' ],
  [ 'Cocos (Keeling) Islands', 'CC' ],
  [ 'Colombia', 'CO' ],
  [ 'Comoros', 'KM' ],
  [ 'Congo', 'CG' ],
  [ 'Congo, Democratic Republic', 'CD' ],
  [ 'Cook Islands', 'CK' ],
  [ 'Costa Rica', 'CR' ],
  [ 'Cote d\'Ivoire', 'CI' ],
  [ 'Croatia', 'HR' ],
  [ 'Cuba', 'CU' ],
  [ 'Cyprus', 'CY' ],
  [ 'Czech Republic', 'CZ' ],
  [ 'Denmark', 'DK' ],
  [ 'Diego Garcia', 'DG' ],
  [ 'Djibouti', 'DJ' ],
  [ 'Dominica', 'DM' ],
  [ 'Dominican Republic', 'DO' ],
  [ 'East Timor', 'TP' ],
  [ 'Ecuador', 'EC' ],
  [ 'Egypt', 'EG' ],
  [ 'El Salvador', 'SV' ],
  [ 'Equatorial Guinea', 'GQ' ],
  [ 'Eritrea', 'ER' ],
  [ 'Estonia', 'EE' ],
  [ 'Ethiopia', 'ET' ],
  [ 'Falkland Islands', 'FK' ],
  [ 'Faroe Islands', 'FO' ],
  [ 'Fiji', 'FJ' ],
  [ 'Finland', 'FI' ],
  [ 'France', 'FR' ],
  [ 'French Guiana', 'GF' ],
  [ 'French Polynesia', 'PF' ],
  [ 'French Southern Territories', 'TF' ],
  [ 'Gabon', 'GA' ],
  [ 'Gambia', 'GM' ],
  [ 'Georgia', 'GE' ],
  [ 'Germany', 'DE' ],
  [ 'Ghana', 'GH' ],
  [ 'Gibraltar', 'GI' ],
  [ 'Greece', 'GR' ],
  [ 'Greenland', 'GL' ],
  [ 'Grenada', 'GD' ],
  [ 'Guadeloupe', 'GP' ],
  [ 'Guam', 'GU' ],
  [ 'Guatemala', 'GT' ],
  [ 'Guinea', 'GN' ],
  [ 'Guinea-Bissau', 'GW' ],
  [ 'Gurnsey', 'GG' ],
  [ 'Guyana', 'GY' ],
  [ 'Haiti', 'HT' ],
  [ 'Heard and Mc Donald Islands', 'HM' ],
  [ 'Holy See - Vatican City', 'VA' ],
  [ 'Honduras', 'HN' ],
  [ 'Hong Kong', 'HK' ],
  [ 'Hungary', 'HU' ],
  [ 'Iceland', 'IS' ],
  [ 'India', 'IN' ],
  [ 'Indonesia', 'ID' ],
  [ 'Iran', 'IR' ],
  [ 'Iraq', 'IQ' ],
  [ 'Ireland', 'IE' ],
  [ 'Isle of Man', 'IM' ],
  [ 'Israel', 'IL' ],
  [ 'Italy', 'IT' ],
  [ 'Jamaica', 'JM' ],
  [ 'Japan', 'JP' ],
  [ 'Jersey', 'JE' ],
  [ 'Jordan', 'JO' ],
  [ 'Kazakstan', 'KZ' ],
  [ 'Kenya', 'KE' ],
  [ 'Kiribati', 'KI' ],
  [ 'Korea, North', 'KP' ],
  [ 'Korea, South', 'KR' ],
  [ 'Kuwait', 'KW' ],
  [ 'Kyrgyzstan', 'KG' ],
  [ 'Laos', 'LA' ],
  [ 'Latvia', 'LV' ],
  [ 'Lebanon', 'LB' ],
  [ 'Lesotho', 'LS' ],
  [ 'Liberia', 'LR' ],
  [ 'Libya', 'LY' ],
  [ 'Liechtenstein', 'LI' ],
  [ 'Lithuania', 'LT' ],
  [ 'Luxembourg', 'LU' ],
  [ 'Macau', 'MO' ],
  [ 'Macedonia', 'MK' ],
  [ 'Madagascar', 'MG' ],
  [ 'Malawi', 'MW' ],
  [ 'Malaysia', 'MY' ],
  [ 'Maldives', 'MV' ],
  [ 'Mali', 'ML' ],
  [ 'Malta', 'MT' ],
  [ 'Marshall Islands', 'MH' ],
  [ 'Martinique', 'MQ' ],
  [ 'Mauritania', 'MR' ],
  [ 'Mauritius', 'MU' ],
  [ 'Mayotte', 'YT' ],
  [ 'Micronesia', 'FM' ],
  [ 'Moldova', 'MD' ],
  [ 'Monaco', 'MC' ],
  [ 'Mongolia', 'MN' ],
  [ 'Montserrat', 'MS' ],
  [ 'Morocco', 'MA' ],
  [ 'Mozambique', 'MZ' ],
  [ 'Myanmar', 'MM' ],
  [ 'Namibia', 'NA' ],
  [ 'Nauru', 'NR' ],
  [ 'Nepal', 'NP' ],
  [ 'Netherlands', 'NL' ],
  [ 'Netherlands Antilles', 'AN' ],
  [ 'New Caledonia', 'NC' ],
  [ 'New Zealand', 'NZ' ],
  [ 'Nicaragua', 'NI' ],
  [ 'Niger', 'NE' ],
  [ 'Nigeria', 'NG' ],
  [ 'Niue', 'NU' ],
  [ 'Norfolk Island', 'NF' ],
  [ 'Northern Mariana Islands', 'MP' ],
  [ 'Norway', 'NO' ],
  [ 'Oman', 'OM' ],
  [ 'Pakistan', 'PK' ],
  [ 'Palau', 'PW' ],
  [ 'Palestinian Territory', 'PS' ],
  [ 'Panama', 'PA' ],
  [ 'Papua New Guinea', 'PG' ],
  [ 'Paraguay', 'PY' ],
  [ 'Peru', 'PE' ],
  [ 'Philippines', 'PH' ],
  [ 'Pitcairn', 'PN' ],
  [ 'Poland', 'PL' ],
  [ 'Portugal', 'PT' ],
  [ 'Puerto Rico', 'PR' ],
  [ 'Qatar', 'QA' ],
  [ 'Reunion', 'RE' ],
  [ 'Romania', 'RO' ],
  [ 'Russia', 'RU' ],
  [ 'Rwanda', 'RW' ],
  [ 'St. Barthélemy', 'BL' ],
  [ 'St. Helena', 'SH' ],
  [ 'St. Kitts and Nevis', 'KN' ],
  [ 'St. Lucia', 'LC' ],
  [ 'St. Martin', 'MF' ],
  [ 'St. Pierre and Miquelon', 'PM' ],
  [ 'St. Vincent - Grenadines', 'VC' ],
  [ 'Samoa (Independent)', 'WS' ],
  [ 'San Marino', 'SM' ],
  [ 'Sao Tome and Principe', 'ST' ],
  [ 'Saudi Arabia', 'SA' ],
  [ 'Senegal', 'SN' ],
  [ 'Seychelles', 'SC' ],
  [ 'Sierra Leone', 'SL' ],
  [ 'Singapore', 'SG' ],
  [ 'Slovakia', 'SK' ],
  [ 'Slovenia', 'SI' ],
  [ 'Solomon Islands', 'SB' ],
  [ 'Somalia', 'SO' ],
  [ 'South Africa', 'ZA' ],
  [ 'South Georgia - South Sandwich', 'GS' ],
  [ 'Spain', 'ES' ],
  [ 'Sri Lanka', 'LK' ],
  [ 'Sudan', 'SD' ],
  [ 'Suriname', 'SR' ],
  [ 'Svalbard - Jan Mayen Islands', 'SJ' ],
  [ 'Swaziland', 'SZ' ],
  [ 'Sweden', 'SE' ],
  [ 'Switzerland', 'CH' ],
  [ 'Syria', 'SY' ],
  [ 'Taiwan', 'TW' ],
  [ 'Tajikistan', 'TJ' ],
  [ 'Tanzania', 'TZ' ],
  [ 'Thailand', 'TH' ],
  [ 'Togo', 'TG' ],
  [ 'Tokelau', 'TK' ],
  [ 'Tonga', 'TO' ],
  [ 'Trinidad and Tobago', 'TT' ],
  [ 'Tristan da Cunha', 'TA' ],
  [ 'Tunisia', 'TN' ],
  [ 'Turkey', 'TR' ],
  [ 'Turkmenistan', 'TM' ],
  [ 'Turks and Caicos Islands', 'TC' ],
  [ 'Tuvalu', 'TV' ],
  [ 'Uganda', 'UG' ],
  [ 'Ukraine', 'UA' ],
  [ 'United Arab Emirates', 'AE' ],
  [ 'United Kingdom', 'GB' ],
  [ 'United States Minor Islands', 'UM' ],
  [ 'Uruguay', 'UY' ],
  [ 'Uzbekistan', 'UZ' ],
  [ 'Vanuatu', 'VU' ],
  [ 'Venezuela', 'VE' ],
  [ 'Viet Nam', 'VN' ],
  [ 'Virgin Islands (British)', 'VG' ],
  [ 'Virgin Islands (U.S.)', 'VI' ],
  [ 'Wallis and Futuna Islands', 'WF' ],
  [ 'Western Sahara', 'EH' ],
  [ 'Yemen', 'YE' ],
  [ 'Yugoslavia', 'YU' ],
  [ 'Zaire', 'ZR' ],
  [ 'Zambia', 'ZM' ],
  [ 'Zimbabwe', 'ZW' ],
  [ 'Unspecified or Unknown', 'ZZ' ]
  ]
  
LANGUAGE_OPTIONS = [
  [ 'English', '00' ],
  [ 'Spanish', '01' ],
  [ 'Farsi (Persian)', '16' ],
  [ 'French', '17' ],
  [ 'German', '18' ],
  [ 'Japanese', '08' ],
  [ 'Korean', '04' ],
  [ 'Mandarin (Putonghua)', '07' ],
  [ 'Pilipino (Tagalog)', '05' ],
  [ 'Portuguese', '06' ],
  [ 'Punjabi', '28' ],
  [ 'Russian', '29' ],
  [ 'Serbo-Croatian (Serbian)', '52' ],
  [ 'Tigrinya', '57' ],
  [ 'Vietnamese', '02' ],
  [ 'Albanian', '56' ],
  [ 'American Sign Language', '37' ],
  [ 'Arabic', '11' ],
  [ 'Armenian', '12' ],
  [ 'Assyrian', '42' ],
  [ 'Bosnian', '58' ],
  [ 'Burmese', '13' ],
  [ 'Cantonese', '03' ],
  [ 'Cebuano (Visayan)', '36' ],
  [ 'Chaldean', '54' ],
  [ 'Chamorro (Guamanian)', '20' ],
  [ 'Chaozhou (Chaochow)', '39' ],
  [ 'Croatian', '14' ],
  [ 'Dutch', '15' ],
  [ 'Greek', '19' ],
  [ 'Gujarati', '43' ],
  [ 'Hebrew', '21' ],
  [ 'Hindi', '22' ],
  [ 'Hmong', '23' ],
  [ 'Hungarian', '24' ],
  [ 'Ilacano', '25' ],
  [ 'Indonesian', '26' ],
  [ 'Italian', '27' ],
  [ 'Khmer (Cambodian)', '09' ],
  [ 'Khmu', '50' ],
  [ 'Kurdish', '51' ],
  [ 'Lahu', '47' ],
  [ 'Lao', '10' ],
  [ 'Marshallese', '48' ],
  [ 'Mien (Yao)', '44' ],
  [ 'Mixteco', '49' ],
  [ 'Pashto', '40' ],
  [ 'Polish', '41' ],
  [ 'Rumanian', '45' ],
  [ 'Samoan', '30' ],
  [ 'Serbian', '31' ],
  [ 'Taiwanewe', '46' ],
  [ 'Thai', '32' ],
  [ 'Toishanese', '53' ],
  [ 'Tongan', '34' ],
  [ 'Turkish', '33' ],
  [ 'Ukranian', '38' ],
  [ 'Urdu', '35' ],
  [ 'Other', '99' ] 
  ]
  
PARENT_EDU_OPTIONS = [
  [ 'Not a high school graduate', '14' ],
  [ 'High school graduate', '13' ],
  [ 'Some college (including AA Degree)', '12' ],
  [ 'College graduate', '11' ],
  [ 'Graduate school', '10' ],
  [ 'Unknown or decline to state', '15' ] ]
  
PARENT_REL_OPTIONS = [
  [ 'Mother', 'mother' ],
  [ 'Father', 'father' ],
  [ 'Stepmother', 'stepmother' ],
  [ 'Stepfather', 'stepfather' ],
  [ 'Grandmother', 'grandmother' ],
  [ 'Grandfather', 'grandfather' ],
  [ 'Aunt', 'aunt' ],
  [ 'Uncle', 'uncle' ],
  [ 'Guardian', 'guardian' ],
  [ 'Deceased', 'deceased' ],
  [ 'Other', 'other' ] ]

EMERG_REL_OPTIONS = [
  [ 'Friend', 'friend' ],
  [ 'Child care', 'childcare' ],
  [ 'Father', 'father' ],
  [ 'Mother', 'mother' ],
  [ 'Son', 'son' ],
  [ 'Daughter', 'daughter' ],
  [ 'Father-in-law', 'father-in-law' ],
  [ 'Mother-in-law', 'mother-in-law' ],
  [ 'Brother', 'brother' ],
  [ 'Sister', 'sister' ],
  [ 'Spouse', 'spouse' ],
  [ 'Partner', 'partner' ],
  [ 'Husband', 'husband' ],
  [ 'Wife', 'wife' ],
  [ 'Stepmother', 'stepmother' ],
  [ 'Stepfather', 'stepfather' ],
  [ 'Grandmother', 'grandmother' ],
  [ 'Grandfather', 'grandfather' ],
  [ 'Aunt', 'aunt' ],
  [ 'Uncle', 'uncle' ],
  [ 'Niece', 'niece' ],
  [ 'Nephew', 'nephew' ],
  [ 'Guardian', 'guardian' ],
  [ 'Other', 'other' ] ]

HEALTH_INS_TYPE_OPTIONS = [ 
  [ 'Private Health Insurance', 'private' ],
  [ 'Healthy Families', 'hfam' ],
  [ 'CaliforniaKids', 'cakids' ],
  [ 'Medi-Cal', 'medi-cal' ],
  [ 'None', 'none' ] ]

UNLISTED_OPTIONS = [
  [ 'Listed', 0 ],
  [ 'Unlisted', 1 ] ]

EMAIL_LOCATION_OPTIONS = [
  [ 'Work', 'Work' ],
  [ 'Home', 'Home' ],
  [ 'Both', 'Both' ] ]
  
ELD_OPTIONS = [
  [ 'Not enrolled in any EL program', '6' ],
  [ 'Enrolled in ELD program', '1' ],
  [ 'Enrolled in ELD and SDAIE (no primary language support)', '2' ],
  [ 'Enrolled in ELD and SDAIE with primary language support', '3' ],
  [ 'Enrolled in ELD and academic subjects through primary language', '4' ],
  [ 'Receiving other EL instructional services', '5' ] ]

FLUENCY_OPTIONS = [
  [ 'English is only language spoken', '1' ],
  [ 'English Learner', '3' ],
  [ 'Initially classified as Fluent-English Proficient', '2' ],
  [ 'Reclassified as Fluent-English Proficient', '4' ] ]

SPED504_OPTIONS = [
  [ 'Not in any special ed. or 504 plan', '100' ],
  [ 'Has disability and receives special ed. services', '001' ],
  [ 'Has a section 504 plan', '010' ] ]

DISABILITY_OPTIONS = [
  [ 'No disability', '000' ],
  [ 'MR', '010' ],
  [ 'HH', '020' ],
  [ 'DEAF', '030' ],
  [ 'SLI', '040' ],
  [ 'VI', '050' ],
  [ 'ED', '060' ],
  [ 'OI', '070' ],
  [ 'OHI', '080' ],
  [ 'SLD', '090' ],
  [ 'DB', '100' ],
  [ 'MD', '110' ],
  [ 'AUT', '120' ],
  [ 'TBI', '130' ] ]

CLASS_SIZE_REDUCTION_OPTIONS = [
  [ 'Full day', '10' ],
  [ 'Half day', '01' ] ]

# intent to return form
  
WILL_ATTEND_OPTIONS = [ 
  [ 'Will be attending a District school', 'attending' ],
  [ 'Will have graduated', 'nr-graduated' ],
  [ 'Will not be attending a District school', 'nr-permanent' ], 
  [ 'Is temporarily leaving the District (but may return later)', 'nr-temporary' ],
  [ 'Not sure - don\'t know at this time', 'unknown' ] ]

ENTRY_CODE_OPTIONS = [
  [ 'TM', 'Temporary status' ],
  [ 'ND', 'New to district' ],
  [ 'RD', 'Returned to district' ],
  [ 'PI', 'Promoted at the same school' ],
  [ 'PS', 'Promoted from another school' ],
  [ 'RT', 'Retained at same grade level' ],
  [ 'DM', 'Demoted to lower grade level' ]  ]

EXIT_CODE_OPTIONS = [
  [ 'Not applicable', '' ],
  [ 'Will attend another public school in California', '160' ],
  [ 'Will attend a private school in California', '180' ],
  [ 'Will attend a US school outside California', '200' ],
  [ 'Will be home schooled', '460' ],
  [ 'Is moving to another country', '240' ],
  [ 'Other reason or don\'t know', '400' ] ]

GRADE_5_MUSIC_OPTIONS = [
  [ '5th Grade Chorus', 'chorus' ],
  [ '5th Grade Beginnning Band', 'band' ] ]
  
GRADE_6_MUSIC_OPTIONS = [
  [ '6th Grade Chorus', 'chorus' ],
  [ '6th Grade Intermediate Band', 'band' ] ]
  
GRADE_78_BAND_OPTIONS = [
  [ 'No Band', '' ],
  [ 'Concert Band in 0 Period', 'band' ] ]

GRADE_78_CHOIR_OPTIONS = [
  [ 'No Choir', '' ],
  [ 'Concert Choir in 0 Period', 'choir' ] ]
  
GRADE_8_ENRICHMENT_OPTIONS = [
  [ 'Art', 'art' ],
  [ 'Drama', 'drama' ],
  [ 'Video', 'video' ],
  [ 'Wood Shop', 'shop' ] ]
